# .github/dependabot.yml

version: 2
updates:
  # 为 pnpm 启用版本更新检查
  - package-ecosystem: "pnpm" # <-- 这里是关键，从 "npm" 改为 "pnpm"
    # pnpm-lock.yaml 和 package.json 所在的目录
    directory: "/"
    # 检查更新的频率
    schedule:
      interval: "daily" # 每天检查一次
    # 给 Dependabot 创建的 PR 自动打上标签
    labels:
      - "dependencies"

    # (可选) 如果你想对某些更新采用更激进的自动合并策略，可以添加如下配置。
    # 例如，对于开发依赖 (devDependencies)，可以允许 major 版本的更新。
    # 对于大多数项目，简单配置就足够了，主要依靠 GitHub 的设置。
