version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "daily"           # 仍然每天检查
      time: "02:00"               # 选一个业务低峰期
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"              # 便于过滤
    target-branch: "main"         # 默认 main，可按需调整
    versioning-strategy: "auto"   # 默认策略；若只想自动合并补丁/小版本，可改为 "widen" 等
    allow:
      - dependency-type: "direct" # 只更新直接依赖；若希望包含间接依赖，可去掉这一段
    reopen-pull-requests: true    # 尝试重开之前被关闭的 PR
    open-pull-requests-limit: 5   # 避免同时过多 PR
    groups:                       # 根据实际情况组合依赖，减少 PR 数量（可选）
      prod-deps:
        dependency-type: "direct"
        patterns:
          - "*"
