version: 2

updates:
  - package-ecosystem: "npm"            # 对 pnpm 也是用 npm 生态
    directory: "/"                      # package.json / pnpm-lock.yaml 所在目录
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    target-branch: "main"
    versioning-strategy: "increase"     # 仅自动提升到满足 semver 的更高版本，可按需调成 "auto" / "widen"
    allow:
      - dependency-type: "direct"       # 如需开发依赖或传递依赖也更新，可调整
    open-pull-requests-limit: 5
    groups:
      pnpm-direct-deps:
        dependency-type: "direct"
        patterns:
          - "*"
    # 可选：指定使用 pnpm-lock.yaml
    registries:                         # 如果用私服，可在 workflows/Dependabot registries 配置
      - type: npm-registry
        url: https://registry.npmjs.org/
    # 注意：Dependabot 会自动检测 pnpm-lock.yaml；若仓库还有 package-lock或 yarn-lock，要删除避免冲突
